---
- name: reload nginx
  service: name=nginx state=reloaded
  sudo_user: root

- name: restart nginx
  service: name=nginx state=restarted
  sudo_user: root

- name: kill gunicorn
  command: killall gunicorn
  sudo_user: root

- name: reload supervisor 
  command: supervisorctl reload
  sudo_user: root
  
- name: restart supervisor
  command: supervisorctl restart all
  sudo_user: root
