---

- name: Install PostgreSQL
  apt: name={{ item }} update_cache=true state=installed
  with_items:
    - postgresql-9.3
    - postgresql-contrib-9.3
    - libpq-dev
    - python-psycopg2
  tags: packages

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  sudo_user: postgres
  postgresql_db: name={{ db_name }}
                 state=present

- name: Ensure user has access to the database
  sudo_user: postgres
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present

- name: Ensure user does not have unnecessary privileges
  sudo_user: postgres
  postgresql_user: name={{ db_user }}
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
                   state=present

- name: Install postgresql configuration files.
  template: src="{{ item }}.j2"
            dest="/etc/postgresql/9.3/main/{{ item }}"
  with_items: conf_files
  notify: restart postgresql
