---

- name: Create the project directory.
  file: state=directory 
        path={{ project_root }}

- name: Create the code directory.
  file: state=directory 
        path={{ project_code_real }}

- name: Create symlink to the current version's code
  file: state=link
        src={{ project_code_real }}
        dest={{ project_code }}
  tags: symlink

- name: Create the venv directory.
  file: state=directory 
        path={{ project_venv_real }}

- name: Create symlink to the current version's venv
  file: state=link
        src={{ project_venv_real }}
        dest={{ project_venv }}
  tags: symlink

- name: Create the project script directory
  file: state=directory
        path={{ project_scripts }}

- name: Create user.
  user: home={{ project_home }}
        name={{ project_name }}
        state=present

- name: Create the .ssh directory.
  file: state=directory 
        path="{{ project_home }}/.ssh/"

- name: Make user the owner of the project directories
  command: "chown -R {{ project_name }}:{{ project_name }} {{ project_root }}"
