---

- name: Install supervisor
  apt: name=supervisor state=installed
  tags: packages


- name: Install supervisord init configs.
  template: src="{{ item }}.j2"
            dest="/etc/supervisor/conf.d/{{ item }}"
  with_items: supervisord_confs
  notify: reload supervisor
