---

- name: Install required system packages.
  apt: pkg={{ item }} 
       state=installed 
       update-cache=yes
  with_items: system_packages

- name: Install required Python packages.
  easy_install: name={{ item }}
  with_items: python_packages

- name: Create the project directory.
  file: state=directory 
        path={{ project_root }}
        state=directory
        mode=755

- name: Create user.
  user: home={{ project_root_home }}
        name={{ project_name }}
        state=present

- name: Set project directory owner
  file: path={{ project_root }}
        owner={{ project_name }}
        group={{ project_name }}

- name: Create the code directory.
  file: group={{ project_name }}
        owner={{ project_name }} 
        mode=755 
        state=directory 
        path={{ project_root_code }}

- name: Create the .ssh directory.
  file: group={{ project_name }}
        owner={{ project_name }}
        mode=755 
        state=directory 
        path="{{ project_root_home }}/.ssh/"
